fix: new on update workAv3.yaml

diff --git a/.github/workflows/workAv3.yaml b/.github/workflows/workAv3.yaml
--- a/.github/workflows/workAv3.yaml
+++ b/.github/workflows/workAv3.yaml
@@ -24,9 +24,9 @@ jobs:
         run: |
           COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
           echo "Commit message: $COMMIT_MSG"
-          if ([[ ! "$COMMIT_MSG" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?:.+$ ]]); then
-            echo "error: invalid commit message"
-            exit 1
+          if [[ ! "$COMMIT_MSG" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?:.+$ ]]; then
+          echo "error: invalid commit message"
+          exit 1
           fi
           
   teste:
